### ISSUE TITLE
Prototype if QueryError can be SingleError and MultipleErrors

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#150] opened 2020-07-07 09:13 UTC
As of https://github.com/alex-dukhno/database/issues/101#issuecomment-654045561 it is preferable to send multiple constraint errors at once if user made errors for multiple columns. That introduce some code duplications in https://github.com/alex-dukhno/database/pull/147 to properly handle UX behaviour

What I'd like to do is to see if `QueryError` became `enum` again with `Single` and `Multiple` variants.

**Comment by AndrewBregger** [comment] 2020-07-08 18:52
@alex-dukhno could you assign this to me? Thanks.

**Comment by AndrewBregger** [comment] 2020-07-08 22:21
@alex-dukhno I have a couple of ways to implement this that I would like to get your opinion on.

1. The first method that I have implemented at the time of writing is:
```rust
pub enum QueryError {
    Single(QueryErrorInner),
    Multiple(Vec<QueryErrorInner>)
}

pub(crate) struct QueryErrorInner {
    severity: Severity,
    code: String,
    kind: QueryErrorKind,
}
```
The problem is this requires `QueryErrorInner` to be public which is something I am trying to avoid doing. That is a simple fix though.

2. The second option is to use a builder pattern where only the builder and QueryError is public. Basically, this would move all of the constructors from the `QueryError` namespace to the builder's namespace.
```rust
pub struct ErrorBuilder {
     errors: Vec<QueryErrorInner>
}

impl ErrorBuilder {
     /// numeric out of range constructor
    pub fn push_out_of_range(&mut self, ty: PostgreSqlType) {
       self.errors.push(....);
    }

    pub fn build() -> QueryError {
         <if only one error build single otherwise build multiple variant>
    }
}
```

3. The last option I have is to sort of combine the approaches above. The structure is laid out below and the explanation follows.
```rust
pub struct QueryError {
    errors: Vec<QueryErrorInner>
}

impl QueryError {
    /// numeric out of range constructor
    pub fn push_out_of_range(&mut self, ty: PostgreSqlType) {
        let err = QueryErrorInner {
                severity: Severity::Error,
                code: "22003".to_owned(),
                kind: QueryErrorKind::NumericTypeOutOfRange(ty),
            };
        self.errors.push(err);
    }

    pub fn push_table_does_not_exist(&mut self, table_name: String) -> Self {
        let err = QueryErrorInner {
            severity: Severity::Error,
            code: "42P01".to_owned(),
            kind: QueryErrorKind::TableDoesNotExist(table_name),
        };
        self.errors.push(err);
    }
}
```
This implementation stores all errors as a vector no matter if there is only one. This would map closely to how messages are generated and it also simplifies the current implementation, I am unsure how this would affect maintainability. 

The explanation is lacking but I think the core snippets explain enough. What are your thoughts?

**Comment by AndrewBregger** [comment] 2020-07-08 23:51
Everyone's opinion is welcome of course.

**Comment by alex-dukhno** [comment] 2020-07-09 15:10
I am in favour of combining second and third variants `ErrorBuilder` makes "collecting" errors explicit. `QueryError` is a `struct` which `sql_engine` uses to talk with `protocol` let's make it as simple as possible for now.

**Closed** 2020-07-11 07:58 UTC
Labels: C-Query Engine, P-High, help wanted
